
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'yellow_cab'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'yellow_cab'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# # Dynamic paths to support parallel runs
# log-path: "logs/{{ run_started_at.strftime('%Y%m%d_%H%M%S') }}_{{ invocation_id }}"
# target-path: "target/{{ run_started_at.strftime('%Y%m%d_%H%M%S') }}_{{ invocation_id }}"

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

# Configuring seeds
seeds:
  yellow_cab:
    reference:
      database: "{{ env_var('ENV_CODE') | trim }}_{{ env_var('PROJ_CODE') | trim }}_RAW_DB"
      schema: seed
    trip:
      database: "{{ env_var('ENV_CODE') | trim }}_{{ env_var('PROJ_CODE') | trim }}_RAW_DB"
      schema: yellow_taxi

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  yellow_cab:
    materialized: table
    +persist_docs:
      relation: true
      columns: true
      
    stage:
      dim:
        database: "{{ env_var('ENV_CODE') | trim }}_{{ env_var('PROJ_CODE') | trim }}_STAGING_DB"
        schema: dim
        materialized: view
      fact:
        database: "{{ env_var('ENV_CODE') | trim }}_{{ env_var('PROJ_CODE') | trim }}_STAGING_DB"
        schema: fact
        materialized: view

    dw:
      dim:
        database: "{{ env_var('ENV_CODE') | trim }}_{{ env_var('PROJ_CODE') | trim }}_DW_DB"
        schema: dim
        materialized: table
      fact:
        database: "{{ env_var('ENV_CODE') | trim }}_{{ env_var('PROJ_CODE') | trim }}_DW_DB"
        schema: fact
        materialized: table

on-run-end:
  - "{{ grant_select_on_schemas([[env_var('ENV_CODE')~'_'~env_var('PROJ_CODE')~'_RAW_DB' | trim, 'YELLOW_TAXI'], [env_var('ENV_CODE')~'_'~env_var('PROJ_CODE')~'_DW_DB' | trim, 'DIM'], [env_var('ENV_CODE')~'_'~env_var('PROJ_CODE')~'_DW_DB' | trim, 'FACT']], env_var('ENV_CODE')~'_'~env_var('PROJ_CODE')~'_STREAMLIT_ROLE') }}"