dbt-postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('ENV_CODE') | trim }}_{{ env_var('PROJ_CODE') | trim }}_DBT_USER"
      password: "{{ env_var('POSTGRES_PWD') }}"
      port: 5432
      dbname: postgres
      schema: demo
      threads: 3
      keepalives_idle: 0 # default 0, indicating the system default

