DROP DATABASE TST_ENTECHLOG_RAW_DB;
DROP DATABASE TST_ENTECHLOG_STAGING_DB;
DROP DATABASE TST_ENTECHLOG_DW_DB;

DROP WAREHOUSE TST_ENTECHLOG_DBT_WH_XS;
DROP WAREHOUSE TST_ENTECHLOG_STREAMLIT_WH_XS;

DROP USER TST_ENTECHLOG_DBT_ROLE;
DROP ROLE TST_ENTECHLOG_DBT_ROLE;

DROP USER TST_ENTECHLOG_STREAMLIT_USER;
DROP ROLE TST_ENTECHLOG_STREAMLIT_ROLE;
