-- Create role and user
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS TST_ENTECHLOG_DBT_ROLE;
CREATE USER IF NOT EXISTS TST_ENTECHLOG_DBT_USER DEFAULT_ROLE = TST_ENTECHLOG_DBT_ROLE;
GRANT ROLE TST_ENTECHLOG_DBT_ROLE TO USER TST_ENTECHLOG_DBT_USER;

ALTER USER TST_ENTECHLOG_DBT_USER SET PASSWORD = '<password>';

-- Create warehouse
USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE TST_ENTECHLOG_DBT_WH_XS
WITH 
WAREHOUSE_SIZE = 'XSMALL' 
WAREHOUSE_TYPE = 'STANDARD' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 1 
SCALING_POLICY = 'ECONOMY' 
COMMENT = 'Warehouse for DBT';

--GRANT required access to the role
GRANT USAGE ON WAREHOUSE TST_ENTECHLOG_DBT_WH_XS TO ROLE TST_ENTECHLOG_DBT_ROLE;

-- Create demo database, Replace will remove old database with same name. So be careful when running create database with replace
CREATE OR REPLACE DATABASE TST_ENTECHLOG_RAW_DB;
CREATE OR REPLACE DATABASE TST_ENTECHLOG_STAGING_DB;
CREATE OR REPLACE DATABASE TST_ENTECHLOG_DW_DB;

-- Create schema
USE DATABASE TST_ENTECHLOG_RAW_DB;
CREATE SCHEMA SEED;
CREATE SCHEMA YELLOW_TAXI;

USE DATABASE TST_ENTECHLOG_STAGING_DB;
CREATE SCHEMA DIM;
CREATE SCHEMA FACT;

USE DATABASE TST_ENTECHLOG_DW_DB;
CREATE SCHEMA DIM;
CREATE SCHEMA FACT;

-- Grant access
GRANT USAGE ON DATABASE TST_ENTECHLOG_RAW_DB TO TST_ENTECHLOG_DBT_ROLE;
GRANT USAGE ON DATABASE TST_ENTECHLOG_STAGING_DB TO TST_ENTECHLOG_DBT_ROLE;
GRANT USAGE ON DATABASE TST_ENTECHLOG_DW_DB TO TST_ENTECHLOG_DBT_ROLE;

GRANT ALL ON SCHEMA TST_ENTECHLOG_RAW_DB.SEED TO TST_ENTECHLOG_DBT_ROLE;
GRANT ALL ON SCHEMA TST_ENTECHLOG_RAW_DB.YELLOW_TAXI TO TST_ENTECHLOG_DBT_ROLE;

GRANT ALL ON SCHEMA TST_ENTECHLOG_STAGING_DB.DIM TO TST_ENTECHLOG_DBT_ROLE;
GRANT ALL ON SCHEMA TST_ENTECHLOG_STAGING_DB.FACT TO TST_ENTECHLOG_DBT_ROLE;

GRANT ALL ON SCHEMA TST_ENTECHLOG_DW_DB.DIM TO TST_ENTECHLOG_DBT_ROLE;
GRANT ALL ON SCHEMA TST_ENTECHLOG_DW_DB.FACT TO TST_ENTECHLOG_DBT_ROLE;