-- Create warehouse
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE DBT_WH
WITH 
WAREHOUSE_SIZE = 'XSMALL' 
WAREHOUSE_TYPE = 'STANDARD' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE 
MIN_CLUSTER_COUNT = 1 
MAX_CLUSTER_COUNT = 2 
SCALING_POLICY = 'ECONOMY' 
COMMENT = 'Warehouse for DBT';

-- Create demo database, Replace will remove old database with same name. So be careful when running create database with replace
CREATE OR REPLACE DATABASE DEMO_DB;

-- Create schema
CREATE SCHEMA "DEMO_DB"."RAW";
CREATE SCHEMA "DEMO_DB"."PREP";
CREATE SCHEMA "DEMO_DB"."ANALYTICS";

-- Create Role
CREATE OR REPLACE ROLE "DBT_ROLE";

-- Create User
CREATE OR REPLACE USER DBT_USER PASSWORD = 'dbtuser' 
	MUST_CHANGE_PASSWORD = FALSE
	DEFAULT_WAREHOUSE = DBT_WH 
	DEFAULT_ROLE = DBT_ROLE;

-- Grant all required access

-- Grant role to the user
GRANT ROLE "DBT_ROLE" TO ROLE "SYSADMIN";
GRANT ROLE "DBT_ROLE" TO USER "DBT_USER";

-- Grant warehouse usage access to role
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;

GRANT CREATE SCHEMA ON DATABASE DEMO_DB TO DBT_ROLE;
GRANT ALL ON SCHEMA RAW TO DBT_ROLE;
GRANT ALL ON SCHEMA PREP TO DBT_ROLE;
GRANT ALL ON SCHEMA ANALYTICS TO DBT_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE DEMO_DB TO DBT_ROLE;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DEMO_DB TO DBT_ROLE;

GRANT SELECT ON ALL TABLES IN DATABASE DEMO_DB TO DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN DATABASE DEMO_DB TO DBT_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE DEMO_DB TO DBT_ROLE;
GRANT SELECT ON FUTURE VIEWS IN DATABASE DEMO_DB TO DBT_ROLE;

GRANT MANAGE GRANTS ON ACCOUNT TO ROLE DBT_ROLE;

-- Validate Access
SHOW GRANTS ON SCHEMA RAW;
SHOW GRANTS ON SCHEMA PREP;
SHOW GRANTS ON SCHEMA ANALYTICS;
SHOW GRANTS TO USER DBT_USER;