dbt-snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWSQL_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('ENV_CODE') | trim }}_SVC_{{ env_var('PROJ_CODE') | trim }}_SNOW_DBT_USER"
      password: "{{ env_var('SNOWSQL_PWD') }}"

      role: "{{ env_var('ENV_CODE') | trim }}_SVC_{{ env_var('PROJ_CODE') | trim }}_SNOW_DBT_ROLE"
      database: "{{ env_var('ENV_CODE') | trim }}_{{ env_var('PROJ_CODE') | trim }}_PREP_DB"
      warehouse: "{{ env_var('ENV_CODE') | trim }}_{{ env_var('PROJ_CODE') | trim }}_DBT_WH_XS"
      schema: UTIL
      threads: 1
      client_session_keep_alive: False